version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "${EXPOSED_API_PORT}:3000"
    environment:
      - NODE_ENV
      - API_VERSION
      - NYTIMES_BOOKS_API_BASEURL
      - NYTIMES_BOOKS_API_KEY
      - GOOGLE_BOOKS_API_KEY
      - GOOGLE_BOOKS_API_BASEURL
      - ALLOWED_API_KEYS
    restart: unless-stopped
    networks:
      - idt

networks:
  idt:
    driver: bridge
